status_html: data/status/pulsar.html
result_filename: data/p3_test_driver/results/%(test)s_%(test_uuid)s.json
test_driver_log_filename: data/logs/p3_test_driver.log
ssh_user: ec2-user
ssh_identity_file: ~/.ssh/pulsar_aws
terraform: true
ansible: true # Requires ../driver-pulsar/deploy/vars.yaml
